### ISSUE TITLE
BE Create Teacher,Section,Room

### ISSUE THREAD

**Issue by Diethertapat** [IT3B-CS3-2016/TheModulo#15]

**Comment by JesraelCruz** [comment]
![createRoomDb.png](https://zube.io/files/it3b-cs3-2016/4c37dbf15afb1722e66c4e69e2e7e853.png)
![createStudentDb.png](https://zube.io/files/it3b-cs3-2016/03960714f045d03b8b2c5293ea17a9d3.png)
![createTeacherDb.png](https://zube.io/files/it3b-cs3-2016/a0376b35b976cdb65f2731fa2f75a935.png)
