### ISSUE TITLE
BE Scheduling

### ISSUE THREAD

**Issue by Diethertapat** [IT3B-CS3-2016/TheModulo#18]

**Comment by JesraelCruz** [comment]
![BE1.png](https://zube.io/files/IT3B-CS3-2016/29f155fb4fe8b5b804edd85175410f44.png)

**Comment by JesraelCruz** [comment]
![BE2.png](https://zube.io/files/IT3B-CS3-2016/ed5aadf2efac17715831055bf7593550.png)

**Comment by JesraelCruz** [comment]
![BE3.png](https://zube.io/files/IT3B-CS3-2016/cbdf8a129453cec92d6325c4a7e2ae3f.png)
