### ISSUE TITLE
Front End Design (Delete Teacher,Section,Room)

### ISSUE THREAD

**Issue by Diethertapat** [IT3B-CS3-2016/TheModulo#2]

**Comment by JesraelCruz** [comment]
![deleteSections.png](https://zube.io/files/it3b-cs3-2016/c6e13c7b3342d202be1186b115de39df.png)
![deleteRooms.png](https://zube.io/files/it3b-cs3-2016/e89e397121cff602cf93fca6b8a14732.png)
![deleteTeacher.png](https://zube.io/files/it3b-cs3-2016/869c28d2c5325da8a4814ef67f7899db.png)
