### ISSUE TITLE
Front End Design (Update Teacher,Section,Room)

### ISSUE THREAD

**Issue by Diethertapat** [IT3B-CS3-2016/TheModulo#21]

**Comment by JesraelCruz** [comment]
![roomSched.png](https://zube.io/files/it3b-cs3-2016/ea3e3addb8437ed9df2baa0e694b2198.png)
![sectionSched.png](https://zube.io/files/it3b-cs3-2016/5c999ec6248ee51703e7bb62c0b86b6f.png)
![teacherSched.png](https://zube.io/files/it3b-cs3-2016/de9311fb87bfe1bb27d4635f49fcf793.png)
