### ISSUE TITLE
Front End Design (Create Teacher,Section,Room)

### ISSUE THREAD

**Issue by Diethertapat** [IT3B-CS3-2016/TheModulo#4]

**Comment by JesraelCruz** [comment]
![createRoom.png](https://zube.io/files/it3b-cs3-2016/f983d041049c88583ad6ac476ecb7743.png)
![createStudent.png](https://zube.io/files/it3b-cs3-2016/bc6d996090846f7eca4225a9c187a909.png)
![createTeacher.png](https://zube.io/files/it3b-cs3-2016/9f9a33f7023c3c663ca1a4ff2c988af3.png)
